"""changed up Shift model to include for OFF block

Revision ID: 65b27ea29aa3
Revises: a922d0a29989
Create Date: 2025-12-04 17:11:14.039904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65b27ea29aa3'
down_revision = 'a922d0a29989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
