"""added columns to schedule model for custom shifts

Revision ID: ef37915748d1
Revises: 65b27ea29aa3
Create Date: 2025-12-06 16:15:18.565808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef37915748d1'
down_revision = '65b27ea29aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('custom_end_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('custom_end_time')
        batch_op.drop_column('custom_start_time')

    # ### end Alembic commands ###
